" TODO: http://stackoverflow.com/questions/95072/what-are-your-favorite-vim-tricks/225852#225852
" General "{{{
set nocompatible  " disable vi compatibility.
set autowrite  " Writes on make/shell commands
set timeoutlen=600  " Time to wait after ESC (default causes an annoying delay)
" set clipboard+=unnamed  " Yanks go on clipboard instead.
if $TMUX == ''
    set clipboard=unnamed
endif
set pastetoggle=<F10> "  toggle between paste and normal: for 'safer' pasting from keyboard
set tags=./tags;$HOME " walk directory tree upto $HOME looking for tags
" Modeline
set modeline
set modelines=5 " default numbers of lines to read for modeline instructions
" Backup
set nowritebackup
set nobackup
set directory=/tmp// " prepend(^=) $HOME/.tmp/ to default path; use full path as backup filename(//)
" Buffers
set hidden " The current buffer can be put to the background without writing to disk
" Match and search
set hlsearch    " highlight search
set ignorecase  " Do case in sensitive matching with
set smartcase       " be sensitive when there's a capital letter
" "}}}
" Formatting "{{{
set fo+=o " Automatically insert the current comment leader after hitting 'o' or 'O' in Normal mode.
set fo-=r " Do not automatically insert a comment leader after an enter
set fo-=t " Do no auto-wrap text using textwidth (does not apply to comments)

set nowrap
set textwidth=0     " Don't wrap lines by default
set wildmode=longest,list " At command line, complete longest common string, then list alternatives.

set tabstop=4    " Set the default tabstop
set softtabstop=4
set shiftwidth=4 " Set the default shift width for indents
set expandtab   " Make tabs into spaces (set by tabstop)

set cindent
set cinoptions=:s,ps,ts,cs
set cinwords=if,else,while,do,for,switch,case

filetype plugin indent on             " Automatically detect file types.
" HTML Formatting
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
let g:html_indent_inctags = "html,body,head,tbody,div,table,tr,p"

" PHP Formatting
let g:PHP_outdentphpescape = 1
let g:PHP_removeCRwhenUnix = 1
let g:PHP_outdentSLComments = 1
let g:PHP_default_indenting = 1
let g:PHP_vintage_case_default_indent = 1
" "}}}
" Visual "{{{
set number  " Line numbers off
set showmatch  " Show matching brackets.
set matchtime=5  " Bracket blinking.
set novisualbell  " No blinking
set noerrorbells  " No noise.
set laststatus=2  " Always show status line.
set vb t_vb= " disable any beeps or flashes on error
set shortmess=atI " Shortens messages

set nolist " Display unprintable characters f12 - switches

set foldenable " Turn on folding
set foldmethod=marker " Fold on the marker
set foldlevel=0 " Don't autofold anything (but I can still fold manually)
set foldopen=block,hor,mark,percent,quickfix,tag " what movements open folds

"set mouse-=a   " Disable mouse
set mousehide  " Hide mouse after chars typed

set splitbelow
set splitright

" "}}}

" Command and Auto commands " {{{
" Sudo write
comm! W exec 'w !sudo tee % > /dev/null' | e!

"Auto commands
au BufRead,BufNewFile {Gemfile,Rakefile,Capfile,*.rake,config.ru}     set ft=ruby
au BufRead,BufNewFile {*.md,*.mkd,*.markdown}                         set ft=markdown
au BufRead,BufNewFile {*.taskpaper}                                   set ft=taskpaper
au BufRead,BufNewFile {*.less}                                        set ft=less
au BufRead,BufNewFile {*.html}                                        set ft=twig
au BufRead,BufNewFile {*.tex}                                         nnoremap <F2> :!make<CR>
au BufRead,BufNewFile *.pde                                           set filetype=arduino
au BufRead,BufNewFile *.ino                                           set filetype=arduino
au BufRead,BufNewFile {COMMIT_EDITMSG}                                set ft=gitcommit

au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | execute "normal g'\"" | endif " restore position in file
" " }}}

" GUI Fonts " {{{
if has("gui_running")
  if has("gui_gtk2")
    " set guifont=Inconsolata\ 12
    set guifont=DejaVu\ Sans\ Mono\ 12
  elseif has("gui_win32")
    " set guifont=Consolas:h11:cANSI
    set guifont=Liberation_Mono_for_Powerline:h10
  endif
endif
" }}}
" Key mappings " {{{
let mapleader = ","
let maplocalleader = ","
if has('win32') || has('win64')
    set directory=.,$TEMP " Swap file support for windows.
    nnoremap <silent> <LocalLeader>vs :source $HOME/_vimrc<CR>
    nnoremap <silent> <LocalLeader>vt :tabnew $HOME/_vimrc<CR>
    nnoremap <silent> <LocalLeader>ve :e $HOME/_vimrc<CR>
    nnoremap <silent> <LocalLeader>vd :e $HOME/.vim/ <CR>
    nnoremap <silent> <LocalLeader>tn :e ~/Dropbox/TaskPaper/Todo.taskpaper<CR>
    nnoremap <silent> <LocalLeader>ts :e ~/Dropbox/TaskPaper/TodoSomeday.taskpaper<CR>
else
    nnoremap <silent> <LocalLeader>vs :source ~/git/vim/vimrc<CR>
    nnoremap <silent> <LocalLeader>vt :tabnew ~/git/vim/vimrc<CR>
    nnoremap <silent> <LocalLeader>ve :e ~/.dotfiles/vim/vimrc<CR>
    nnoremap <silent> <LocalLeader>vd :e ~/.vim/ <CR>
    nnoremap <silent> <LocalLeader>tn :e ~/Dropbox/todo.txt<CR>
    nnoremap <silent> <LocalLeader>tn :e ~/todo.txt<CR>
    " nnoremap <silent> <LocalLeader>ts :e ~/Dropbox/TaskPaper/TodoSomeday.taskpaper<CR>
endif

nnoremap <silent> <LocalLeader><Space> :noh<CR>
nnoremap <silent> <Space>b :LustyJuggler<CR>

" Buffer maps
"" Close buffer without closing split
nmap <silent> <LocalLeader>d :bp\|bd #<CR>
"" Next buffer
nmap <silent> <LocalLeader>n :bn<CR>
"" Previous buffer
nmap <silent> <LocalLeader>n :bp<CR>

" Split line(opposite to S-J joining line)
nnoremap <silent> <C-J> gEa<CR><ESC>ew

" Add a new line at the end of the line.
map <S-CR> A<CR><ESC>

" Control+S and Control+Q are flow-control characters: disable them in your terminal settings.
" $ stty -ixon -ixoff
noremap <C-S> :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>

" show/Hide hidden Chars
map <silent> <F12> :set invlist<CR>

" generate HTML version current buffer using current color scheme
map <silent> <LocalLeader>2h :runtime! syntax/2html.vim<CR>
" " }}}
" Setting up Vundle - the vim plugin bundler"{{{
let iCanHazNeo=1
if has('win32') || has('win64')
    set runtimepath=$HOME/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$HOME/.vim/after,$HOME/.vim/bundle/neobundle.vim/

    let neobundle_readme=expand('$HOME/.vim/bundle/neobundle.vim/README.md')
    if !filereadable(neobundle_readme)
        echo "Installing NeoBundle.."
        echo ""
        silent :exe '!mkdir -p ' . $HOME .'/.vim/bundle'
        silent :exe '!git clone https://github.com/shougo/neobundle.vim '. $HOME .'/.vim/bundle/neobundle.vim'
        let iCanHazNeo=0
    endif
else
    let neobundle_readme=expand('~/.vim/bundle/neobundle.vim/README.md')
    if !filereadable(neobundle_readme)
        echo "Installing Neobundle.."
        echo ""
        silent !mkdir -p ~/.vim/bundle
        silent !git clone https://github.com/shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
        let iCanHazNeo=0
    endif
    set rtp+=~/.vim/bundle/neobundle.vim/
endif"}}}
" Plugins " {{{
filetype off
call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make -f make_mac.mak',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }
NeoBundle 'powerline/fonts', {
\ 'build': {
    \ 'mac': './install.sh',
    \ 'linux': './install.sh',
    \ 'unix': './install.sh',
    \ },
\ }

" colour schemes
NeoBundle 'altercation/vim-colors-solarized'
NeoBundle 'chriskempson/base16-vim'

" trying this
NeoBundle 'YankRing.vim'
let g:yankring_history_dir = $HOME.'/.vim/'
let g:yankring_history_file = '.yankring_history'
NeoBundle 'http://github.com/thinca/vim-poslist.git'
"Bundle "http://github.com/mattn/gist-vim.git"
" Bundle 'taskpaper.vim'
NeoBundle 'https://github.com/mivok/vimtodo'
" Bundle 'https://github.com/mivok/vimtodo'
NeoBundle 'https://github.com/vim-scripts/VOoM'
NeoBundle 'https://github.com/tpope/vim-sensible.git'
NeoBundle 'freitass/todo.txt-vim'
" Bundle 'LustyJuggler'

" Programming
"" Syntax plugins
NeoBundle 'jQuery'
NeoBundle 'tpope/vim-markdown'
NeoBundle 'tpope/vim-cucumber'
NeoBundle 'spf13/vim-preview'
NeoBundle 'markcornick/vim-vagrant'
NeoBundle 'ekalinin/Dockerfile.vim'
NeoBundle 'https://github.com/vim-scripts/autohotkey-ahk'
" Bundle "python_fold_compact"
NeoBundle 'https://github.com/chrisbra/csv.vim'
NeoBundle 'https://github.com/Glench/Vim-Jinja2-Syntax'
NeoBundle 'https://github.com/evidens/vim-twig'
NeoBundle 'leshill/vim-json'

NeoBundle 'https://github.com/groenewege/vim-less'
NeoBundle 'https://github.com/StanAngeloff/php.vim'
NeoBundle 'chase/vim-ansible-yaml'
NeoBundle 'https://github.com/digitaltoad/vim-jade'
NeoBundle 'Matt-Deacalion/vim-systemd-syntax'
NeoBundle 'mustache/vim-mustache-handlebars'
NeoBundle 'https://github.com/jplaut/vim-arduino-ino'
NeoBundle 'evanmiller/nginx-vim-syntax'
NeoBundle 'myhere/vim-nodejs-complete'
NeoBundle 'pangloss/vim-javascript'
NeoBundle 'othree/javascript-libraries-syntax.vim'
NeoBundle 'matthewsimo/angular-vim-snippets'
NeoBundle 'claco/jasmine.vim'
NeoBundle 'burnettk/vim-angular'

" syntax for haml, sass and scss.
NeoBundle 'tpope/vim-haml'
" sytax for html5
" NeoBundle 'Valloric/YouCompleteMe', {
"      \ 'build' : {
"      \     'mac' : 'git submodule update --init --recursive; ./install.sh --clang-completer --system-libclang --omnisharp-completer',
"      \     'unix' : './install.sh --clang-completer --system-libclang --omnisharp-completer',
"      \     'windows' : './install.sh --clang-completer --system-libclang --omnisharp-completer',
"      \     'cygwin' : './install.sh --clang-completer --system-libclang --omnisharp-completer'
"      \    }
"      \ }

" Snippets
" Bundle 'http://github.com/gmarik/snipmate.vim.git'
"NeoBundle 'SirVer/ultisnips'
" Trigger configuration. Do not <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsSnippetDirectories=["ultisnips"]
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"


" Git integration
" git integration for vim.
NeoBundle 'fugitive.vim'
" extended support for git in vim.
NeoBundle 'gregsexton/gitv'
" Bundle "https://github.com/airblade/vim-gitgutter"

" Latex Editing
" a latex editing plugin.
NeoBundle 'LaTeX-Box'

" (HT|X)ml tool
" A plugin for writing html fast
NeoBundle 'mattn/emmet-vim'
"Bundle 'ragtag.vim' " A set of useful mappings for working with html and other web languages.

" Utility
NeoBundle 'sudo.vim'
" help in alignment of latex tabular tables and other text.
NeoBundle 'Align'
" improved motion support, do double leader then motion button.
NeoBundle 'Lokaltog/vim-easymotion'
" shows the list of open buffers in the command bar.
NeoBundle 'https://github.com/bling/vim-bufferline'
" Allows cleaning up whitespace.
NeoBundle 'https://github.com/bronson/vim-trailing-whitespace'
" File search plugin
NeoBundle 'https://github.com/kien/ctrlp.vim'
" Adds a list of tags (Function names etc)
NeoBundle 'https://github.com/majutsushi/tagbar'
" Syntax checker for programming languages.
NeoBundle 'https://github.com/scrooloose/syntastic'
" Extra language support for syntastic
NeoBundle 'https://github.com/myint/syntastic-extras'
" comments and uncomments lines using gcc
NeoBundle 'https://github.com/tpope/vim-commentary.git'
" Useful mappings for various things (buffer navigation, etc)
NeoBundle 'https://github.com/tpope/vim-unimpaired.git'
NeoBundle 'https://github.com/tpope/vim-vinegar'
" allows better support for dates with CTRL+A and CTRL+X
NeoBundle 'http://github.com/tpope/vim-speeddating'
" makes it so that plugins can use the '.' shortcut
NeoBundle 'repeat.vim'
" Allows surrounding text with tags, quotes, etc.
NeoBundle 'surround.vim'
" Indentation guides
"NeoBundle 'https://github.com/nathanaelkane/vim-indent-guides'
NeoBundle 'Indent-Guides'
NeoBundle 'taxilian/vim-web-indent'
" Auto closing of brackets
NeoBundle 'Raimondi/delimitMate'
" Visualise undo tree
NeoBundle 'mbbill/undotree'
" Tabulate code and other text
NeoBundle 'godlygeek/tabular'
" PHP Integration for Vim
NeoBundle 'spf13/PIV'

" Tab completion NeoBundle 'ervandew/supertab'
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'Shougo/neosnippet'
NeoBundle 'scrooloose/snipmate-snippets'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'honza/vim-snippets'
NeoBundle 'haya14busa/incsearch.vim'
NeoBundle 'https://github.com/vim-scripts/hexman.vim'
NeoBundle 'https://github.com/vim-scripts/DrawIt'
NeoBundle 'HTML-AutoCloseTag'
NeoBundle 'ChrisYip/Better-CSS-Syntax-for-Vim'

NeoBundle 'vim-scripts/LargeFile'
let g:LargeFile=1

" allows zooming in on an invididual split.
NeoBundle 'ZoomWin'
"noremap <LocalLeader>o :ZoomWin<CR>
"vnoremap <LocalLeader>o <C-C>:ZoomWin<CR>
"inoremap <LocalLeader>o <C-O>:ZoomWin<CR>
noremap <C-W>+o :ZoomWin<CR>

" Ag
" Allows using Ag to search files from within vim.
NeoBundle 'rking/ag.vim'
" " Ack
" " Allows using ack to search files from within vim.
" Bundle 'ack.vim'
" noremap <LocalLeader># "ayiw:Ack <C-r>a<CR>
" vnoremap <LocalLeader># "ay:Ack <C-r>a<CR>

" vim-airline
NeoBundle 'https://github.com/bling/vim-airline'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

if v:version > 701
  NeoBundle 'zhaocai/GoldenView.Vim'
endif
let g:goldenview__enable_default_mapping=0

call neobundle#end()

if iCanHazNeo == 0
    echo "Installing Bundles, please ignore key map error messages"
    echo ""
    :NeoBundleInstall
endif
filetype plugin indent on
" " }}}
" Gui and theme options"{{{
if has('gui_running')
    set background=dark
    set guioptions-=m
    set guioptions-=T
    set guioptions-=r
else
    set background=dark
endif

if &term =~ '256color'
    " disable Background Color Erase (BCE) so that color schemes
    " render properly when inside 256-color tmux and GNU screen.
    " see also http://sunaku.github.io/vim-256color-bce.html
    set t_ut=
endif

let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme solarized
"}}}
" Command and Auto commands " {{{
" Sudo write
comm! W exec 'w !sudo tee % > /dev/null' | e!

"Auto commands
au BufRead,BufNewFile {*.php}                                         set ft=php
au BufRead,BufNewFile {*.php}                                         UltiSnipsAddFiletypes php
au BufRead,BufNewFile {Gemfile,Rakefile,Capfile,*.rake,config.ru}     set ft=ruby
au BufRead,BufNewFile {*.md,*.mkd,*.markdown}                         set ft=markdown
au BufRead,BufNewFile {*.taskpaper}                                   set ft=taskpaper
au BufRead,BufNewFile {*.less}                                        set ft=less
au BufRead,BufNewFile {*.html}                                        set ft=twig
au BufRead,BufNewFile {*.jade}                                        set ft=jade
au BufRead,BufNewFile {COMMIT_EDITMSG}                                set ft=gitcommit

au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | execute "normal g'\"" | endif " restore position in file
" " }}}
