#!/usr/bin/env bash
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Script to bootstrap a linux box
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#   Alan Jenkins <alan.james.jenkins@gmail.com>

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

DIR=$(cd $(dirname "$0"); pwd)

###############################################################################
# apt-get
###############################################################################
if [ -x /usr/bin/apt-get ]; then
  if [[ -f $DIR/packages/apt ]]; then
    exec<$DIR/packages/apt
    while read line
    do
      if [[ ! "$line" =~ (^#|^$) ]]; then
        packages="$packages $line"
      fi
    done
    sudo apt-get install $packages
  fi
fi

###############################################################################
# Arch Linux (Pacman & Yaourt)
###############################################################################
if [ -x /usr/bin/pacman ]; then
  if [[ -f $DIR/packages/pacman ]]; then
    exec<$DIR/packages/pacman
    while read line
    do
      if [[ ! "$line" =~ (^#|^$) ]]; then
        packages="$packages $line"
      fi
    done
    sudo pacman -S $packages --noconfirm
  fi
  if [ -x /usr/bin/yaourt ]; then
    if [[ -f $DIR/packages/yaourt ]]; then
      exec<$DIR/packages/yaourt
      while read line
      do
        if [[ ! "$line" =~ (^#|^$) ]]; then
          packages="$packages $line"
        fi
      done
      yaourt -S $packages
    fi
  fi
fi
