#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Customize to your needs...
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
